# Generated by Django 5.1.2 on 2024-10-22 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('theme', models.CharField(max_length=150, verbose_name='Тема сообщение')),
                ('date_sanding', models.DateTimeField(help_text='ДД.ММ.ГГГГ 00:00', verbose_name='Дата отправки')),
                ('date_receiving', models.DateTimeField(help_text='ДД.ММ.ГГГГ 00:00', verbose_name='Дата получения')),
                ('description', models.TextField(verbose_name='Описание или текст сообщения')),
                ('attachment', models.FileField(upload_to='', verbose_name='Вложение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
