# Generated by Django 5.1.2 on 2024-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Вложение'),
        ),
    ]
